setup.py, superbench/common/utils/__init__.py, superbench/common/utils/logging.py
Update logger class.
* add file handler along with stream handler
* add colored formatter
=> Utils: Code Revision - Add file handler along with stream handler, and colored formatter

superbench/benchmarks/docker_benchmarks/docker_base.py, superbench/benchmarks/micro_benchmarks/micro_base.py, superbench/benchmarks/model_benchmarks/model_base.py
Major Revisions
1. Modify result process interface to add more check and return True/False.
2. For MicroBenchmark, there have two function, _process_numeric_result() is to process result from python scripts. _process_raw_result is to process raw string result from system call benchmarks.
3. For DockerBenchmark, only _process_raw_result is needed to process raw string result.
4. For ModelBenchmark, only __process_model_result is needed to process result from python scripts.
=> Benchmarks: Code Revision - Revise result process interface and add result checking

examples/benchmarks/pytorch_bert_large.py, superbench/benchmarks/base.py, superbench/benchmarks/registry.py, tests/benchmarks/model_benchmarks/test_model_base.py, tests/benchmarks/model_benchmarks/test_pytorch_base.py, tests/benchmarks/model_benchmarks/test_pytorch_bert.py, tests/benchmarks/test_registry.py
Major Revisions:
- Add BenchmarkRegistry.create_benchmark_context() to create benchmark context.
- Merge check_parameters() into launch_benchmark() and remove check_parameters().
Minor Revisions:
- Adapt all unit tests.
- Adapt examples to launch benchmark.
=> Benchmarks: Code Revision - Revise BenchmarkRegistry interfaces for integration with executor.

examples/benchmarks/matmul.py, examples/benchmarks/pytorch_bert_large.py, examples/benchmarks/sharding_matmul.py, superbench/benchmarks/micro_benchmarks/__init__.py, superbench/benchmarks/micro_benchmarks/sharding_matmul.py
Major Features:
- Realize ShardingMatmul class.
- Add examples for matmul and sharding_matmul.
Minor Features:
- Add commands into comments for examples.
=> Benchmarks: Add Benchmark - Add op-sharding microbenchmark, including matmul and sharding_matmul.

superbench/benchmarks/base.py
Change the validation of raw data from:
```
instance of List[List[Number]] for BenchmarkType.MODEL, and BenchmarkType.DOCKER.
instance of List[str] for BenchmarkType.MICRO.
```
To
```
instance of List[List[Number]] for BenchmarkType.MODEL.
instance of List[str] for BenchmarkType.DOCKER.
instance of List[List[Number]] or List[str] for BenchmarkType.MICRO.
```
=> Benchmarks: Fix Bug - Fix bug when validate the raw data format.

superbench/config/default.yaml, superbench/executor/__init__.py, superbench/executor/executor.py, tests/executor/test_executor.py
* add executor class
* update default config to exec benchmarks
=> Executor: Init - Add superbench executor class

dockerfile/cuda11.1.1.dockerfile, superbench/config/default.yaml, superbench/executor/executor.py, tests/executor/test_executor.py
* fix missing package in dockerfile
* update benchmark list and parameters
* catch runtime errors
* refine logging info
=> Executor - Fix issues when executing benchmarks

.azure-pipelines/cuda-unit-test.yml, .codecov.yml, .github/workflows/lint.yml, README.md, azure-pipelines.yml, dockerfile/cuda11.1.1.dockerfile
* Rename dev branch to main and set it as default.
=> Setup: Code Revision - Rename dev branch to main in config and readme

examples/benchmarks/pytorch_bert_large.py, superbench/benchmarks/model_benchmarks/pytorch_bert.py, tests/benchmarks/model_benchmarks/test_pytorch_bert.py
- Add self._gpu_available judgement in inference process.
- Set seq_length as 128 for BERT example.
=> Benchmarks: Code Revision - Fix some issue for BERT benchmark.

examples/benchmarks/pytorch_lstm.py, superbench/benchmarks/model_benchmarks/__init__.py, superbench/benchmarks/model_benchmarks/pytorch_bert.py, superbench/benchmarks/model_benchmarks/pytorch_gpt2.py, superbench/benchmarks/model_benchmarks/pytorch_lstm.py, tests/benchmarks/model_benchmarks/test_pytorch_lstm.py
Add LSTM model benchmarks.
- Add PytorchLSTM benchmark class.
- Register 'pytorch-lstm' benchmark.
- Add tests for lstm benchmark.
- Add example for lstm benchmark.
=> Benchmarks: Add Benchmark - Add LSTM model benchmarks.

superbench/benchmarks/model_benchmarks/pytorch_cnn.py, superbench/benchmarks/model_benchmarks/pytorch_lstm.py
Specify the correct precision type when create training data for CNN and LSTM benchmarks.
=> Benchmarks: Fix Bug - Fix dataset precision for CNN and LSTM benchmarks.

.clang-format, .editorconfig, .github/workflows/lint.yml, Makefile
* add clang-format to lint cpp sources
* add cpp lint in GitHub Actions
=> Setup - Add lint for cpp sources

.azure-pipelines/ansible-integration-test.yml, superbench/runner/playbooks/deploy.yaml, superbench/runner/runner.py, tests/ansible/Vagrantfile, tests/ansible/hosts.ini, tests/ansible/test.sh, tests/ansible/tests/test_check_env.yaml, tests/ansible/tests/test_deploy.yaml
__Major Revision__
* Add integration tests for Ansible playbooks.
__Minor Revision__
* Add `gpu_vendor` var to bypass gpu mount.
=> CI/CD - Add integration tests for Ansible playbooks

.azure-pipelines/cuda-unit-test.yml
Reverse the order of cppbuild and lint in cuda test pipeline
=> CI/CD - Reorder cuda test pipeline

superbench/executor/executor.py, tests/executor/test_executor.py
__Major Revision__
* Save benchmark results to json file.
=> Executor - Save benchmark results to file

superbench/benchmarks/micro_benchmarks/cublas_function.py
Add error return code for cublas microbenchmark
=> Benchmarks: Code Revision - add error return code for cublas microbenchmark

.azure-pipelines/cuda-unit-test.yml, dockerfile/cuda11.1.1.dockerfile, setup.py, superbench/common/utils/__init__.py, superbench/common/utils/nvidia_helper.py
Add nvml package as the utility of benchmarks.
- Add nvml package as the utility of benchmarks.
- get_device_compute_capability() function is supported.
=> Benchmarks: Add Feature - Add nvml package to provide python interfaces of nvidia.

setup.py, superbench/benchmarks/model_benchmarks/pytorch_cnn.py, superbench/benchmarks/registry.py, superbench/common/utils/logging.py, superbench/config/default.yaml, superbench/executor/executor.py, tests/executor/test_executor.py
Fix bugs and refine log in single GPU benchmarks.
__Minor Revisions__
- Fix none framework issue.
- Fix empty parameter bug.
- Remove missed mobilenet_v3 models.
- Change benchmark registration log to debug level.
- Add pid in logging.
- Add missing benchmarks in default config.
=> Bug bash - Fix bugs and refine log in single GPU benchmarks

.dockerignore, .github/workflows/build-image.yml, dockerfile/cuda11.1.1.dockerfile, third_party/Makefile
Update packages and add build cache for CUDA 11.1.1 Dockerfile.
* remove duplicate cmake and ompi, which are already in base image
* add hpcx and sharp lib
* add cache for gitmodules build
=> Dockerfile - Update CUDA 11.1.1 Dockerfile

MANIFEST.in, setup.py, superbench/cli/_handler.py, superbench/common/utils/file_handler.py, superbench/common/utils/logging.py, superbench/config/default.yaml, superbench/runner/playbooks/check_env.yaml, superbench/runner/playbooks/deploy.yaml, superbench/runner/runner.py, tests/cli/test_sb.py, tests/executor/test_executor.py, tests/runner/test_runner.py
Fix bugs in multi GPU benchmarks.
- Add sb deploy content
- Fix inline if-expression syntax
- Fix quote escape issue in bash command
- Add custom env in config
- Update default config for multi GPU
- Fix wrong parameters in torch distributed microbenchmarks
- Update MANIFEST.in to include jinja2 template
- Require jinja2 minimum version
- Fix occasional duplicate output in Ansible runner
- Fix mixed color issue in log
=> Bug bash - Fix bugs in multi GPU benchmarks

superbench/benchmarks/model_benchmarks/pytorch_base.py, tests/benchmarks/model_benchmarks/test_pytorch_base.py
Replace torch.optim.AdamW with transformers.AdamW to align with previous testing. (transformers.AdamW is about 20% faster than Replace torch.optim.AdamW)
=> Benchmarks: Code Revision - Replace torch.optim.AdamW with transformers.AdamW.

superbench/benchmarks/micro_benchmarks/gemm_flops_performance.py, tests/benchmarks/micro_benchmarks/test_gemm_flops_performance.py
The order of changing the kernels and generating the commands is reversed.
=> Benchmarks: Fix Bug - Fix gemm kernel bug for nvidia v100.

docs/cli.md, superbench/cli/_commands.py, superbench/cli/_handler.py, superbench/common/utils/__init__.py, superbench/common/utils/file_handler.py, superbench/executor/executor.py, superbench/runner/runner.py, tests/executor/test_executor.py, tests/runner/test_runner.py
Support custom output directory.
- Support custom output directory for sb run/exec.
- Reuse output directory for all benchmarks in one run.
__Minor Revisions__
- Update document accordingly.
=> CLI - Support custom output directory

superbench/common/utils/file_handler.py, superbench/executor/executor.py, tests/executor/test_executor.py
- Fix race condition issue when multi ranks rotating the same directory.
=> Bug Fix -  Fix race condition issue for multi ranks

superbench/common/devices/__init__.py, superbench/common/devices/gpu.py, superbench/executor/executor.py, superbench/runner/playbooks/deploy.yaml, superbench/runner/runner.py, tests/ansible/tests/test_deploy.yaml, tests/executor/test_executor.py
Support both NVIDIA and AMD GPU and check GPU vendor during deployment and execution.
* Add GPU environment check in `sb deploy`
* Check GPU vendor in executor.
=> Runner & Executor - Support AMD GPU

superbench/config/amd_mi100.yaml, superbench/config/amd_mi100_z53.yaml
Keep the settings to align with previous tests.
=> Benchmarks: Add Configuration - Add validation config file for AMD MI100

.azure-pipelines/ansible-integration-test.yml, .azure-pipelines/cpu-unit-test.yml, .azure-pipelines/cuda-unit-test.yml, .codecov.yml, .github/workflows/build-image.yml, .github/workflows/gh-pages.yml, .github/workflows/lint.yml
Update pipeline for release branch.
=> CI/CD - Update pipeline for release branch

superbench/executor/executor.py
Fix bug when convert bool config to store_true argument.
=> Bug Fix - Fix bug when convert bool config to store_true argument.

.azure-pipelines/ansible-integration-test.yml, .azure-pipelines/cpu-unit-test.yml, .azure-pipelines/cuda-unit-test.yml, .codecov.yml, .github/workflows/build-image.yml, .github/workflows/gh-pages.yml, .github/workflows/lint.yml, superbench/common/utils/file_handler.py, superbench/executor/executor.py, tests/executor/test_executor.py
Cherry-pick the bug fix from release 0.2 to main, contains:
- #117 
- #120 
- #122
=> Bug bash - Merge fix from release/0.2 to main

superbench/common/utils/__init__.py, superbench/common/utils/network.py, tests/benchmarks/micro_benchmarks/test_computation_communication_overlap.py, tests/benchmarks/micro_benchmarks/test_sharding_matmul.py, tests/benchmarks/utils.py
Update network common utils.
- Add get_ib_devices in network common utils 
- Move get_free_port from test utils to network common utils
=> Utils: Code Revision - Update network common utils

.gitmodules, dockerfile/cuda11.1.1.dockerfile, third_party/Makefile
Add nccl-tests as a submodule and add build logic.
- Add nccl-tests as submodule
- Add build script for it.
=> Benchmarks: Build Pipeline - Add nccl-tests as a submodule and add build logic.

.gitmodules, dockerfile/cuda11.1.1.dockerfile, third_party/Makefile
Add perftest as a submodule of superbench.
- Add perftest as submodule
- Add build script for it.
=> Benchmarks: Build Pipeline - Add perftest as a submodule and add build logic

tests/executor/test_executor.py
Fix bug of tests/executor/test_executor.
- Test default enabled benchmarks only instead of all benchmarks.
=> Benchmarks: Fix bug - fix bug in test_executor.py to test default enabled tests only

examples/benchmarks/disk_performance.py, superbench/benchmarks/micro_benchmarks/__init__.py, superbench/benchmarks/micro_benchmarks/disk_performance.py, superbench/config/default.yaml, tests/benchmarks/micro_benchmarks/test_disk_performance.py, tests/executor/test_executor.py
Add disk performance microbenchmark.
- Add microbenchmark, example, test, config for disk performance.
- Fix bugs in executor unit test related to default enabled tests.
=> Benchmarks: Add Benchmark - Add disk performance benchmark

superbench/runner/playbooks/deploy.yaml
Fix Ansible connection issue when running in localhost.
=> Bug Fix - Fix Ansible connection issue in localhost

superbench/benchmarks/micro_benchmarks/rocm_common.cmake
Support rocm cmake build. 
- Add  some envs in rocm_common.cmake to support rocm cmake build.
=> Benchmarks: Build Pipeline - Support rocm cmake build

dockerfile/cuda11.1.1.dockerfile, third_party/Makefile
Support rocm in third_party/makefile.
- Split rocm and cuda target in makefile
- Add target in dockerfile
=> Benchmarks: Build Pipeline - Support rocm in third_party/makefile

README.md, docs/getting-started/installation.md, docs/getting-started/run-superbench.md, superbench/__init__.py, website/docusaurus.config.js, website/package-lock.json, website/package.json
Update version in packages and docs.
=> Release - Update version 0.2.1 in packages and docs

README.md, docs/getting-started/installation.md, docs/getting-started/run-superbench.md, superbench/__init__.py, superbench/benchmarks/model_benchmarks/pytorch_base.py, superbench/runner/playbooks/deploy.yaml, website/docusaurus.config.js, website/package-lock.json, website/package.json
Cherry-pick bug fixes from v0.2.1 to main.
* Fix bug of VGG models failed on A100 GPU with batch_size=128.
* Fix Ansible connection issue when running in localhost.
* Update version in packages and docs.
=> Release - SuperBench v0.2.1

examples/benchmarks/nccl_bw_performance.py, superbench/benchmarks/micro_benchmarks/cuda_nccl_bw_performance.py
Add rccl bandwidth microbenchmark for rocm.
- Register rccl-bw benchmark.
=> Benchmarks: Add Benchmark - Revise and add rccl microbenchmark for rocm.

superbench/benchmarks/__init__.py, superbench/benchmarks/micro_benchmarks/micro_base.py, superbench/benchmarks/reducer.py, superbench/benchmarks/result.py, tests/benchmarks/model_benchmarks/test_model_base.py, tests/benchmarks/test_registry.py, tests/benchmarks/test_result.py
Add reduce function support for output summary.
- Add reducer class to maintain all reduce functions.
- Save reduce type of each metric into `BenchmarkResult`
- Fix UT.
=> Benchmarks: Add Feature - Add reduce function support for output summary.

superbench/benchmarks/micro_benchmarks/cublas_function.py, superbench/benchmarks/micro_benchmarks/micro_base.py, superbench/benchmarks/micro_benchmarks/sharding_matmul.py, superbench/benchmarks/model_benchmarks/model_base.py, tests/benchmarks/model_benchmarks/test_model_base.py
Replace `sum(results) / len(results)` with `statistics.mean(results)`
=> Benchmarks: Code Revision - Calculate average value by using statistics module.

superbench/benchmarks/micro_benchmarks/sharding_matmul.py, superbench/benchmarks/model_benchmarks/model_base.py, tests/benchmarks/model_benchmarks/test_model_base.py
Set reduce type for current benchmarks' metrics, including model benchmarks and ShardingMatmul.
=> Benchmarks: Add Feature - Set reduce type for current benchmarks' metrics.

docs/design-docs/benchmarks.md
Add ReduceType description into benchmarks doc.
=> Benchmarks: Doc Revision - Add ReduceType into benchmarks doc

docs/cli.md, docs/developer-guides/development.md, docs/developer-guides/using-docker.mdx, docs/tutorial/container-images.mdx, website/sidebars.js
Add docs on:
* Docker image tag list
* Build image and run container instructions
=> Docs - Add docs for Docker container and image

docs/design-docs/benchmarks.md, superbench/benchmarks/result.py, tests/benchmarks/model_benchmarks/test_model_base.py, tests/benchmarks/test_registry.py, tests/benchmarks/test_result.py
Change the field name `reduce` to `reduce_op`.
=> Benchmarks: Code Revision - change 'reduce' to 'reduce_op'

.devcontainer/devcontainer.json, .devcontainer/post-create-command.sh, .editorconfig, .vscode/extensions.json, .vscode/launch.json, .vscode/settings.json, docs/developer-guides/development.md
Add config and docs for development experience.
__Major Revision__
- Add settings and extensions config for VSCode.
- Add devcontainer config for Codespaces.
- Update document accordingly.
=> Docs - Add config and docs for development experience

third_party/Makefile
Add build logic of hipBusBandwidth in third_party.
- Add build logic of hipBusBandwidth in third_party
=>  Benchmarks: Build Pipeline - Add build logic of hipBusBandwidth in third_party

tests/benchmarks/micro_benchmarks/test_cuda_nccl_bw_performance.py
fix typo in test_nccl_bw_performance.py.
-  fix typo in test_nccl_bw_performance.py.
=> Benchmarks: Code Revision - fix typo in test of nccl microbenchmark.

examples/benchmarks/rocm_gemm_flops_performance.py, superbench/benchmarks/micro_benchmarks/__init__.py, superbench/benchmarks/micro_benchmarks/rocm_gemm_flops_performance.py, tests/benchmarks/micro_benchmarks/test_rocm_gemm_flops_performance.py
Add gemm flops microbenchmark for amd.
- Add gemm flops microbenchmark for amd.
- Add related example and test file.
=> Benchmarks: Add Benchmark - Add gemm flops microbenchmark for amd

superbench/benchmarks/micro_benchmarks/micro_base.py, superbench/common/utils/__init__.py, superbench/common/utils/process.py
Package frequently-used subprocess invoke into function.
=> Benchmarks: Code Revision - Revise subprocess invoke

setup.py
change the minimal version requirement for superbench:
```
'torch>=1.7.0a0',
'torchvision>=0.8.0a0',
```
=> Setup: Revision - Revise torch extra_require

dockerfile/rocm4.0-pytorch1.7.0.dockerfile, dockerfile/rocm4.2-pytorch1.7.0.dockerfile
Add dockerfile `rocm4.0-pytorch1.7.0.dockerfile` and `rocm4.2-pytorch1.7.0.dockerfile` for `rocm` platform.
=> Dockerfile: Add dockerfile - Add rocm 4.0 and 4.2 dockerfile with pytorch1.7.0

dockerfile/cuda11.1.1.dockerfile, dockerfile/rocm4.0-pytorch1.7.0.dockerfile, dockerfile/rocm4.2-pytorch1.7.0.dockerfile, superbench/runner/playbooks/deploy.yaml
Setup docker environment in docker container.
- Install docker client for cuda and rocm images.
- Mount /var/run/docker.sock from host
=> Benchmarks: Docker Benchmarks - Setup Docker-in-Docker environment 

dockerfile/cuda11.1.1.dockerfile, dockerfile/rocm4.0-pytorch1.7.0.dockerfile, dockerfile/rocm4.2-pytorch1.7.0.dockerfile
Install openmpi-4.0.0 for ROCm images.
=> Dockerfile: Add Package - Install openmpi for ROCm images

superbench/config/amd_mi100_hpe.yaml
fix bug of error param opterations of rccl-bw in hpe MI100 config
- operations->operation
=> Bug - Fix Bug : fix bug of error param in hpe MI100 config

superbench/runner/playbooks/deploy.yaml
Revise 'docker run' in sb deploy due to base image running endpoint/cmd under /root.
- define endpoint bash when 'docker run'
=> Runner: Code Revision - Revise 'docker run' in sb deploy due to base image may running endpoint/cmd under /root

.github/workflows/build-image.yml, superbench/config/amd_mi100_hpe.yaml
Add ROCm image build in GitHub Actions.
=> CI/CD - Add ROCm image build in GitHub Actions

superbench/tools/system_info.py, tests/cli/test_sb.py
Fix function naming issue in system info .
- fix function naming issue in system info 
- save to json file
- add timeout for subprocess.run
- revise error handling to print exception message
=> Bug: Fix bug - Fix function naming issue in system info 

superbench/benchmarks/micro_benchmarks/computation_communication_overlap.py
fix bug in error message of communication-computation-overlap.
- remove non existing variable
=> Benchmark: Fix Bug - fix error message of communication-computation-overlap

.github/workflows/build-image.yml
Fix bug in build image for push event.
- Fix bug in build image for push event when `github.base_ref` is not set.
- Unify `[` and `[[` usage.
=> CI/CD - Fix bug in build image for push event

.github/workflows/lint.yml
Update GitHub Action VM, fix pipeline hanging.
=> CI/CD - Update GitHub Action VM

superbench/config/amd_mi100_hpe.yaml, superbench/config/amd_mi100_z53.yaml, superbench/config/azure_ndv4.yaml, superbench/config/default.yaml
Update benchmarks in configuration files for single node validation of superbench v0.3.
- fix bugs of parameters in nccl-bw for single node validation in configs
- update new benchmarks in amd_mi100_hpe.yaml, amd_mi100_z53.yaml, azure_ndv4.yaml
- fix bug of wrong gpu visible prefix
=> Benchmarks: Update - Update benchmarks in configuration file

README.md, docs/developer-guides/using-docker.mdx, docs/getting-started/installation.md, docs/getting-started/run-superbench.md, docs/superbench-config.mdx, docs/tutorial/container-images.mdx, superbench/__init__.py, superbench/config/amd_mi100_hpe.yaml, superbench/config/amd_mi100_z53.yaml, superbench/config/azure_ndv4.yaml, superbench/config/default.yaml, website/blog/2021-09-22-release-0-3.md, website/docusaurus.config.js, website/package-lock.json, website/package.json
Upgrade version and release note. Closes #95 and #170.
* Upgrade package versions
* Add release note for v0.3.0
=> Docs - Upgrade version and release note

superbench/benchmarks/model_benchmarks/pytorch_base.py
Fix typo when set force_fp32 option.
=> Benchmarks: Fix bug - Fix bug when set force_fp32 option.

dockerfile/rocm4.0-pytorch1.7.0.dockerfile, dockerfile/rocm4.2-pytorch1.7.0.dockerfile
This commit fixes the URL of ROCm GPG file.
=> Dockerfiles: Fix Bug - Fix ROCm GPG file URL

.azure-pipelines/cpu-unit-test.yml, superbench/config/amd_mi100_hpe.yaml, superbench/config/amd_mi100_z53.yaml, superbench/config/azure_ndv4.yaml, superbench/config/default.yaml
Fix config for memory bandwidth test.
=> Bug - Fix configuration for memory bandwidth test

docs/superbench-config.mdx, docs/user-tutorial/benchmarks/docker-benchmarks.md, website/sidebars.js
Update docs to add ORT AMD benchmarks based on docker.
=> Docs: Update docs to add ORT AMD benchmarks based on docker

examples/benchmarks/kernel_launch_overhead.py
Fix typo in description of kernel_launch_overhead.py
Fix typo in description of kernel_launch_overhead.py
Hope this helps :)
=> Benchmarks: Fix Typo - Fix typo in description of kernel launch overhead example

docs/user-tutorial/benchmarks/micro-benchmarks.md
Update gpu-copy benchmark metrics.
=> Docs: Update gpu-copy benchmark metrics

docs/user-tutorial/benchmarks/micro-benchmarks.md
Update ib validtion mirobenchmark metrics.
=> Docs: Update ib validation microbenchmark metrics 

superbench/config/azure_ndmv4.yaml
Add config file for Azure NDm A100 v4 SKU.
=> Benchmarks - Add config file for NDm A100 v4

superbench/config/amd_mi100_hpe.yaml, superbench/config/amd_mi100_z53.yaml, superbench/config/azure_ndmv4.yaml, superbench/config/azure_ndv4.yaml, superbench/config/default.yaml, superbench/executor/executor.py, superbench/runner/ansible.py, superbench/runner/playbooks/deploy.yaml, superbench/runner/playbooks/fetch_results.yaml, superbench/runner/runner.py
Fix issues for distributed runs:
* fix config for memory bandwidth benchmarks
* add throttling for high concurrency docker pull
* update rsync path and exclude directories
* handle exceptions when creating summary
* tune for logging
=> Bug - Fix issues for distributed runs

superbench/cli/_commands.py, superbench/cli/_help.py, superbench/cli/_result_handler.py, tests/cli/test_sb.py
Add cli to integrate data diagnosis module.
=> CLI - Integrate data diagnosis

tests/benchmarks/micro_benchmarks/test_gpu_copy_bw_performance.py
Benchmarks: Fix Comment - Correct benchmark name in test_gpu_copy_bw_performance.py.
=> Benchmarks: Fix Comment - Correct benchmark name in test_gpu_copy_bw_performance.py

docs/user-tutorial/benchmarks/micro-benchmarks.md, superbench/benchmarks/micro_benchmarks/cpu_memory_bw_latency_performance.py, tests/benchmarks/micro_benchmarks/test_cpu_memory_bw_latency_performance.py
Add benchmark metrics for cpu-memory-bw-latency.
=> Docs - Add benchmark metrics for cpu-memory-bw-latency

docs/cli.md, docs/user-tutorial/data-diagnosis.md
=> Docs - Add usage for data diagnosis

dockerfile/rocm4.0-pytorch1.7.0.dockerfile, dockerfile/rocm4.2-pytorch1.7.0.dockerfile
Build openmpi with ucx support in rocm dockerfiles.
=> Bug - Build openmpi with ucx support in rocm dockerfiles

third_party/Makefile
Fix fio build issue (Illegal instruction).
Refer to https://github.com/axboe/fio/issues/970
=> Bug - Fix fio build issue

docs/user-tutorial/benchmarks/micro-benchmarks.md, superbench/benchmarks/micro_benchmarks/cublas_function.py, superbench/benchmarks/micro_benchmarks/cudnn_function.py
Unify metric and add doc for cublas and cudnn functions.
=> Docs - Unify metric and add doc for cublas and cudnn functions

superbench/common/utils/network.py
Fix code insecure issue that binds a socket to all network interfaces.
=> Bug: Fix code insecure issue that binds a socket to all network interfaces

superbench/config/azure_ndmv4.yaml, superbench/config/azure_ndv4.yaml, superbench/config/default.yaml
Disable disk-benchmark in ndmv4.yaml and change batch size to 1 in default.yaml
=> Config - Disable disk-benchmark in ndmv4.yaml and change batch size to 1 in default.yaml

superbench/benchmarks/micro_benchmarks/gpu_copy_performance/gpu_copy.cu
This commit fixes bug of GPU scan logic in bidirectional tests.
=> Benchmarks: Fix Bug - Fix GPU scan logic in gpu_copy

docs/superbench-config.mdx, superbench/runner/runner.py, tests/runner/test_runner.py
Support customized env for all modes in configuration.
=> Config - Support customized env for all modes

docs/cli.md, docs/user-tutorial/data-diagnosis.md, superbench/cli/_help.py
=> Bug - fix typo of format

examples/benchmarks/gpu_copy_bw_performance.py, superbench/benchmarks/micro_benchmarks/gpu_copy_bw_performance.py, superbench/benchmarks/micro_benchmarks/gpu_copy_performance/gpu_copy.cu, superbench/config/amd_mi100_hpe.yaml, superbench/config/amd_mi100_z53.yaml, superbench/config/azure_ndmv4.yaml, superbench/config/azure_ndv4.yaml, superbench/config/default.yaml, tests/benchmarks/micro_benchmarks/test_gpu_copy_bw_performance.py
This commit makes data checking in gpu_copy optional, because it will take too long time if message size is large.
=> Benchmarks: Revise Code - Make data checking in gpu_copy optional

superbench/runner/runner.py
Fix env file path for `docker run`.
=> Bug - Fix env file path

superbench/benchmarks/micro_benchmarks/gpu_copy_performance/gpu_copy.cu
Fix invalid reference of P2P detection result in gpu_copy.
=> Bug Fix - Fix P2P detection in gpu_copy

.github/workflows/build-image.yml, dockerfile/rocm5.0.1-pytorch1.9.0.dockerfile
=> Dockerfile - Add dockerfile for rocm5.0.1

superbench/analyzer/__init__.py, superbench/analyzer/data_diagnosis.py, superbench/analyzer/rule_base.py, tests/analyzer/test_data_diagnosis.py, tests/analyzer/test_rulebase.py
Abstract RuleBase from DataDiagnosis.
=> Analyzer: Revise - Abstract RuleBase from DataDiagnosis

docs/cli.md, superbench/cli/_commands.py, superbench/cli/_help.py, superbench/cli/_result_handler.py, tests/cli/test_sb.py
Integrage result summary and update output format of data diagnosis.
- integrage result summary 
- add md and html format for data diagnosis
=> CLI - Integrage result summary and update output format of data diagnosis

docs/cli.md, superbench/cli/_commands.py, superbench/cli/_help.py, superbench/cli/_result_handler.py, tests/cli/test_sb.py
Integrate output all nodes diagnosis results.
=> CLI - Integrate output all nodes diagnosis results

.github/workflows/build-image.yml, dockerfile/rocm5.1.1-pytorch1.10.0.dockerfile
=> Dockerfile - Add dockerfile for rocm5.1.1

dockerfile/cuda11.1.1.dockerfile, dockerfile/rocm4.0-pytorch1.7.0.dockerfile, dockerfile/rocm4.2-pytorch1.7.0.dockerfile, dockerfile/rocm5.0-pytorch1.9.0.dockerfile, dockerfile/rocm5.0.1-pytorch1.9.0.dockerfile, dockerfile/rocm5.1.1-pytorch1.10.0.dockerfile
Add support to run sb command inside docker image - install missing dependency.
=> Dockerfile - Add support to run sb command inside docker image

docs/cli.md, docs/getting-started/run-superbench.md, setup.py, superbench/benchmarks/build.sh, superbench/cli/_commands.py, superbench/cli/_handler.py, superbench/cli/_help.py, superbench/runner/playbooks/check_env.yaml, superbench/runner/runner.py, tests/cli/test_sb.py, tests/runner/test_runner.py
Support `sb run` on host directly without Docker
- Add `--no-docker` argument for `sb run`.
- Run on host directly if `--no-docker` if specified.
- Update docs and tests correspondingly.
=> Support `sb run` on host directly without Docker

.github/workflows/build-image.yml, dockerfile/cuda11.1.1.dockerfile, dockerfile/rocm5.0.x.dockerfile, dockerfile/rocm5.1.x.dockerfile, third_party/Makefile
Update dependencies and Dockerfile:
* upgrade nccl-tests and rccl-tests to current latest version to match
NCCL/RCCL versions
* unify image tag names on DockerHub
* remove verbose output in Dockerfile and minor fix some flags
=> Update dependencies and Dockerfile

dockerfile/cuda11.1.1.dockerfile, dockerfile/etc/ndv4-topo.xml, setup.py
Add dependencies
* include ndv4-topo.xml in cuda docker images
* require requests version to avoid RequestsDependencyWarning
=> Add dependencies for topo xml

superbench/benchmarks/base.py, superbench/benchmarks/return_code.py, superbench/runner/runner.py, tests/benchmarks/test_base.py
* Gracefully exit when timeout, add corresponding log and return code.
* Set minimum timeout to 1 minute and enlarge Ansible timeout.
=> Gracefully exit when timeout

superbench/analyzer/data_diagnosis.py, tests/data/diagnosis_summary.json
Rename field in data diagnosis to be more readable.
- rename fields according to diagnosis/metric format
- change type of diagnosis/issue_num to be int
=> Analyzer: Rename fields in json of data diagnosis to be more readable

.azure-pipelines/cpu-unit-test.yml, .azure-pipelines/cuda-unit-test.yml, .devcontainer/post-create-command.sh, dockerfile/cuda11.1.1.dockerfile, dockerfile/rocm5.0.x.dockerfile, dockerfile/rocm5.1.x.dockerfile, docs/developer-guides/development.md, setup.py
Update Python setup for require packages.
* downgrade requests version to be compatible with python 3.6, add corresponding pipeline for 3.6
* add extra entry in extras_require for nested packages
* update `pip install` contents accordingly
=> Update Python setup for require packages

dockerfile/cuda11.1.1.dockerfile, dockerfile/rocm5.0.x.dockerfile, dockerfile/rocm5.1.x.dockerfile
Update apt packages in dockerfile, support sudo and ip commands.
=> Update apt packages in dockerfile

docs/getting-started/installation.mdx, website/blog/2022-09-01-release-0-6.md
* Update release note
* Update required Docker version (thanks to @chhwang)
=> Docs - Fix issues in document

.codecov.yml
Update codecov flags in configuration.
=> CI/CD - Update Codecov config

.dockerignore, dockerfile/cuda11.1.1.dockerfile, dockerfile/rocm5.0.x.dockerfile, dockerfile/rocm5.1.x.dockerfile, setup.py, superbench/cli/_handler.py, tests/cli/test_sb.py
Update version to include revision hash and date in `{last tag}+g{git hash}.d{date}` format, here're the examples:
* exact tag: `0.6.0`
* commit after tag: `0.6.0+gcbb1b34`
* commit after tag with local changes: `0.6.0+gcbb1b34.d20221028`
=> CLI - Update version to include revision hash and date

superbench/benchmarks/micro_benchmarks/cuda_memory_bw_performance.py, tests/benchmarks/micro_benchmarks/test_cuda_memory_bw_performance.py
Resolve mem-bw unstable issue.
- add 3 seconds sleep between each bandwidth test command
=> Benchmark: Revision - Add wait time option to resolve mem-bw unstable issue

superbench/benchmarks/micro_benchmarks/ib_validation_performance.py
* Reuse `gen_pair_wise_config` in micro-benchmark
=> Benchmarks - Support `pair-wise` pattern in IB validation benchmark

superbench/benchmarks/micro_benchmarks/cuda_gemm_flops_performance.py
Support GEMM benchmark on Hopper GPUs.
=> Support GEMM benchmark on Hopper GPUs

superbench/benchmarks/model_benchmarks/pytorch_bert.py
Fix bug in TE BERT model, create different instances for each layer during init.
=> Fix bug in TE BERT model

docs/user-tutorial/benchmarks/micro-benchmarks.md, docs/user-tutorial/benchmarks/model-benchmarks.md
Update benchmark doc of cublaslt, cublas-function and model benchmarks
=> Doc - Update benchmark doc

README.md, docs/cli.md, docs/getting-started/installation.mdx, docs/getting-started/run-superbench.md, docs/superbench-config.mdx, docs/user-tutorial/benchmarks/micro-benchmarks.md, docs/user-tutorial/benchmarks/model-benchmarks.md, docs/user-tutorial/container-images.mdx, docs/user-tutorial/data-diagnosis.md, docs/user-tutorial/result-summary.md, superbench/__init__.py, superbench/benchmarks/micro_benchmarks/cublaslt_fp8_gemm/cublaslt_utils.h, superbench/benchmarks/model_benchmarks/pytorch_bert.py, superbench/cli/_commands.py, superbench/cli/_handler.py, superbench/config/amd_mi100_hpe.yaml, superbench/config/amd_mi100_z53.yaml, superbench/config/azure/inference/standard_nc64as_t4_v3.yaml, superbench/config/azure/inference/standard_nc96ads_a100_v4.yaml, superbench/config/azure/inference/standard_nv18ads_a10_v5.yaml, superbench/config/azure_ndmv4.yaml, superbench/config/azure_ndv4.yaml, superbench/config/default.yaml, superbench/runner/playbooks/deploy.yaml, superbench/runner/runner.py, tests/cli/test_sb.py, website/blog/2023-01-20-release-0-7.md, website/docusaurus.config.js, website/package-lock.json, website/package.json
Cherry-pick bug fixes from v0.7.0 to main.
* Benchmarks - Fix missing include in FP8 benchmark (#460)
* Fix bug in TE BERT model (#461)
* Doc - Update benchmark doc (#465)
* Bug: Fix bug for incorrect datatype judgement in cublas-function source code (#464)
* Support `sb deploy` without pulling image (#466)
* Docs - Upgrade version and release note (#467)
Co-authored-by: Russell J. Hewett <russell.j.hewett@gmail.com>
Co-authored-by: Yuting Jiang <yuting.jiang@microsoft.com>
=> Release - SuperBench v0.7.0

.github/workflows/build-image.yml
Free more disk space in GitHub Action VHD.
=> CI/CD - Free disk space in GitHub Action VHD

superbench/benchmarks/model_benchmarks/pytorch_base.py
Update TE FP8 model conversion.
* Add 16-byte alignment comment.
* Fix TE layer parameters type.
=> Benchmark - Update TE FP8 model conversion

setup.py, superbench/analyzer/data_analysis.py, superbench/analyzer/data_diagnosis.py, superbench/analyzer/result_summary.py
Analyzer: Fix bug in python3.8 due to pandas api change.
- force check numeric only in dataframe for analysis
- dataframe.append -> pd.concat
- pd.ExcelWriter.save() -> pd.ExcelWriter.close()
=> Analyzer: Fix bug in python3.8 due to pandas api change

superbench/benchmarks/micro_benchmarks/cudnn_function.py
Fix bug to get metric from cmd when error happens(cudnn-function/_time:4)
=> Bug - Fix bug to get metric from cmd when error happens

superbench/benchmarks/model_benchmarks/model_base.py, superbench/benchmarks/model_benchmarks/pytorch_base.py, tests/benchmarks/model_benchmarks/test_model_base.py
Change num_workers to configurable in data loader.
=> Add num_workers argument in model benchmark

README.md
=> Docs - Update version in README

setup.py
Update error message in setup, require wheel for pip>=23.1.
=> Update error message in setup

superbench/benchmarks/model_benchmarks/pytorch_bert.py, superbench/benchmarks/model_benchmarks/pytorch_gpt2.py
Update 404 outdate reference links.
=> Benchmarks - Update outdate references

superbench/benchmarks/__init__.py, superbench/benchmarks/context.py, superbench/common/devices/gpu.py, superbench/executor/executor.py
Add support for DirectX GPU platform.
- Add DirectX platform for benchmark registry
- Add gpu_vendor identify for AMD and NVIDIA with win driver
=> Benchmarks - Add support for DirectX GPU platform

.github/workflows/build-win.yml, superbench/benchmarks/micro_benchmarks/__init__.py, superbench/benchmarks/micro_benchmarks/directx_mem_bw_performance.py, superbench/benchmarks/micro_benchmarks/directx_mem_bw_performance/BenchmarkOptions.h, superbench/benchmarks/micro_benchmarks/directx_mem_bw_performance/GPUMemRwBw.vcxproj, superbench/benchmarks/micro_benchmarks/micro_base.py, superbench/common/utils/process.py, tests/benchmarks/micro_benchmarks/test_directx_mem_bw_performance.py
add python code for DirecXGPUMemBw.
=> Benchmarks: micro benchmarks - add python code for DirecXGPUMemBw

superbench/benchmarks/micro_benchmarks/__init__.py, superbench/benchmarks/micro_benchmarks/directx_gpu_copy_performance.py, superbench/benchmarks/micro_benchmarks/directx_gpu_copy_performance/GPUCopyBw.vcxproj, superbench/benchmarks/micro_benchmarks/directx_gpu_copy_performance/Main.cpp, tests/benchmarks/micro_benchmarks/test_directx_gpu_copy_performance.py
add python code for DirectXGPUCopy.
=> Benchmarks: micro benchmarks - add python code for DirectXGPUCopy

dockerfile/directx12.dockerfile, superbench/benchmarks/micro_benchmarks/__init__.py, superbench/benchmarks/micro_benchmarks/directx_gpu_encoding_latency.py, tests/benchmarks/micro_benchmarks/test_directx_gpu_encoding_latency.py
add python code for DirectXGPUEncodingLatency.
=> Benchmarks: micro benchmarks - add python code for DirectXGPUEncodingLatency

README.md, docs/getting-started/installation.mdx, docs/getting-started/run-superbench.md, docs/superbench-config.mdx, docs/user-tutorial/container-images.mdx, docs/user-tutorial/data-diagnosis.md, docs/user-tutorial/result-summary.md, superbench/__init__.py, superbench/config/amd_mi100_hpe.yaml, superbench/config/amd_mi100_z53.yaml, superbench/config/azure/inference/standard_nc64as_t4_v3.yaml, superbench/config/azure/inference/standard_nc96ads_a100_v4.yaml, superbench/config/azure/inference/standard_nv18ads_a10_v5.yaml, superbench/config/azure_ndmv4.yaml, superbench/config/azure_ndv4.yaml, superbench/config/default.yaml, website/blog/2023-07-25-release-0-9.md, website/docusaurus.config.js, website/package-lock.json, website/package.json
Upgrade version and release note.
- Upgrade package versions
- Add release note for v0.9.0
=> Docs - Upgrade version and release note 

.github/workflows/build-image.yml, .github/workflows/build-win.yml, README.md, docs/getting-started/installation.mdx, docs/getting-started/run-superbench.md, docs/superbench-config.mdx, docs/user-tutorial/container-images.mdx, docs/user-tutorial/data-diagnosis.md, docs/user-tutorial/result-summary.md, superbench/__init__.py, superbench/benchmarks/micro_benchmarks/directx_gpu_encoding_latency.py, superbench/config/amd_mi100_hpe.yaml, superbench/config/amd_mi100_z53.yaml, superbench/config/azure/inference/standard_nc64as_t4_v3.yaml, superbench/config/azure/inference/standard_nc96ads_a100_v4.yaml, superbench/config/azure/inference/standard_nv18ads_a10_v5.yaml, superbench/config/azure_ndmv4.yaml, superbench/config/azure_ndv4.yaml, superbench/config/default.yaml, third_party/Makefile, website/blog/2023-07-25-release-0-9.md, website/docusaurus.config.js, website/package-lock.json, website/package.json
Cherry-pick bug fixes from v0.9.0 to main.
- CI/CD: pipeline - clean more disk space to fix rocm building image pipeline(#555 )
- Benchmarks: bug fix - use absolute path for input file in DirectXEncodingLatency(#554)
- CI/CD - add push win docker image on release branch in pipeline (#552)
- Docs - Upgrade version and release note(#557)
=> Release - SuperBench v0.9.0

superbench/benchmarks/micro_benchmarks/cuda_nccl_bw_performance.py, tests/benchmarks/micro_benchmarks/test_cuda_nccl_bw_performance.py
Add data type option for nccl tests.
=> Benchmarks: Microbenchmark - Add data type option for NCCL and RCCL tests

superbench/benchmarks/micro_benchmarks/hipblaslt_function.py, tests/benchmarks/micro_benchmarks/test_hipblaslt_function.py
Benchmarks: Micro benchmarks - add fp8 and initialization for hipblaslt benchmark.
=> Benchmarks: Micro benchmarks - add fp8 and initialization for hipblaslt benchmark

dockerfile/cuda11.1.1.dockerfile, dockerfile/cuda12.2.dockerfile, dockerfile/rocm5.0.x.dockerfile, dockerfile/rocm5.1.x.dockerfile, dockerfile/rocm5.7.x.dockerfile, dockerfile/rocm6.0.x.dockerfile
=> Dockerfile - Upgrade mlc to v3.11

.github/workflows/build-image.yml, dockerfile/cuda12.4.dockerfile
Add CUDA 12.4 dockerfile.
- upgrade nvidia docker into 23.04
- upgrade mlc into v3.11
- upgrade hpcx into 2.18
=> Dockerfile - Add CUDA 12.4 dockerfile

dockerfile/cuda11.1.1.dockerfile
Update hpcx link in cuda11.1 dockerfile to fix CI
=> Dockerfile - Update hpcx link in cuda11.1 dockerfile to fix CI

.github/workflows/build-image.yml, README.md, dockerfile/cuda11.1.1.dockerfile, dockerfile/cuda12.4.dockerfile, dockerfile/rocm6.0.x.dockerfile, dockerfile/rocm6.2.x.dockerfile, docs/getting-started/installation.mdx, docs/getting-started/run-superbench.md, docs/superbench-config.mdx, docs/user-tutorial/container-images.mdx, docs/user-tutorial/data-diagnosis.md, docs/user-tutorial/result-summary.md, setup.py, superbench/__init__.py, superbench/common/utils/device_manager.py, superbench/config/amd_mi100_hpe.yaml, superbench/config/amd_mi100_z53.yaml, superbench/config/amd_mi300.yaml, superbench/config/azure/inference/standard_nc64as_t4_v3.yaml, superbench/config/azure/inference/standard_nc96ads_a100_v4.yaml, superbench/config/azure/inference/standard_nv18ads_a10_v5.yaml, superbench/config/azure_ndmv4.yaml, superbench/config/azure_ndv4.yaml, superbench/config/azure_ndv5.yaml, superbench/config/default.yaml, website/blog/2024-09-20-release-0-11.md, website/docusaurus.config.js, website/package-lock.json, website/package.json
Cherry pick bug fixes from v0.11.0 to main
* #645 
* #648 
* #646 
* #647 
* #651 
* #652 
* #650
=> Release - SuperBench v0.11.0

.github/CODEOWNERS
=> Docs - Update CODEOWNERS

setup.py
Fix installation and lint issues:
* Fix transformer installation in Python3.7 due to upgrade of safetensors.
* Fix lint issues in mypy 1.14.1.
=> Setup - Fix installation and lint issues

.github/workflows/build-image.yml
Add image build on arm64 arch.
=> CI/CD - Add image build on arm64 arch

.github/workflows/build-image.yml
Merge multi-arch image in build pipeline.
=> CI/CD - Merge multi-arch image

.github/workflows/build-image.yml, README.md, docs/getting-started/installation.mdx, docs/getting-started/run-superbench.md, docs/superbench-config.mdx, docs/user-tutorial/container-images.mdx, docs/user-tutorial/data-diagnosis.md, docs/user-tutorial/result-summary.md, superbench/__init__.py, superbench/benchmarks/model_benchmarks/megatron_gpt3.py, superbench/config/amd_mi100_hpe.yaml, superbench/config/amd_mi100_z53.yaml, superbench/config/amd_mi300.yaml, superbench/config/azure/inference/standard_nc64as_t4_v3.yaml, superbench/config/azure/inference/standard_nc96ads_a100_v4.yaml, superbench/config/azure/inference/standard_nv18ads_a10_v5.yaml, superbench/config/azure_ndmv4.yaml, superbench/config/azure_ndv4.yaml, superbench/config/azure_ndv5.yaml, superbench/config/default.yaml, website/blog/2025-08-06-release-0-12.md, website/docusaurus.config.js, website/package-lock.json, website/package.json
Cherry-pick bug fixes from v0.12.0 to main.
* #725
* #727
* #728
Co-authored-by: Hongtao Zhang <hongtaozhang@microsoft.com>
Co-authored-by: Yifan Xiong <yixio@microsoft.com>
Co-authored-by: Guoshuai Zhao <guzhao@microsoft.com>
=> Release - SuperBench v0.12.0
