microsoft/superbenchmark

tests/__init__.py
tests/benchmarks/micro_benchmarks/test_sharding_matmul.py
tests/benchmarks/utils.py

Revise benchmark test util to support multi-GPU test
-  simulate Pytorch DDP environment in benchmark test util
-  Add multi-processing logic for multi-GPU benchmark execution and collect results
- Add init.py in 'tests' to identify the 'tests' module

Benchmarks: Revise Test - Revise  benchmark test util to support pytorch multi-GPU test

---

README.md
superbench/benchmarks/base.py
superbench/benchmarks/registry.py
tests/benchmarks/test_registry.py

Add BenchmarkRegistry.get_all_benchmark_predefine_settings() interface to get all predefine parameters of all benchmarks. The result type is dict[str, dict] , key is benchmark name, value is the dict with structure: {'parameter': default_value}. Currently the result looks like:
> {'pytorch-bert-large': {'run_count': 1, 'duration': 0, 'num_warmup': 64, 'num_steps': 2048, 'sample_count': 128, 'batch_size': 32, 'precision': [<Precision.FLOAT32: 'float32'>, <Precision.FLOAT16: 'float16'>], 'model_action': [<ModelAction.TRAIN: 'train'>], 'distributed_impl': None, 'distributed_backend': None, 'no_gpu': False, 'num_classes': 100, 'hidden_size': 1024, 'num_hidden_layers': 24, 'num_attention_heads': 16, 'intermediate_size': 4096, 'seq_len': 512}, 'pytorch-bert-base': {'run_count': …

Benchmarks: Add Feature - Add interface to get all predefine parameters of all benchmarks.

---

superbench/benchmarks/model_benchmarks/model_base.py

Increase the default sample count to make sure it is sufficient for distribution with all workers.
If batch_size = 32, then 1024 is enough for 32 workers to run one step.

Benchmarks: Fix Bug - Increase default sample count for benchmarking.

---

.azure-pipelines/cuda-unit-test.yml
Makefile
dockerfile/cuda11.1.1.dockerfile

Call build script when setup environment.
- Call build script of benchmarks in Makefile, the command is `make cppbuild`
- Add cppbuild command for testing env.
- Add cppbuild command for docker image.

Benchmarks: Build Pipeline - Call build script when setup environment.

---

.azure-pipelines/cuda-unit-test.yml
superbench/benchmarks/build.sh
superbench/benchmarks/micro_benchmarks/kernel_launch_overhead/CMakeLists.txt
superbench/benchmarks/micro_benchmarks/micro_base.py

Revise path of installing cmake projects
- unify SB_MICRO_PATH  to one base path, bin will be installed in SB_MICRO_PATH/bin , library will be installed in SB_MICRO_PATH/lib

Benchmarks: Build Pipeline - Revise path of installing cmake projects

---

superbench/benchmarks/micro_benchmarks/cublas_function.py
superbench/benchmarks/micro_benchmarks/cublas_function/CMakeLists.txt
superbench/benchmarks/micro_benchmarks/cudnn_function.py
superbench/benchmarks/micro_benchmarks/cudnn_function/CMakeLists.txt

Rename bin name of cublas and cudnn microbenchmark to 'cublas_benchmark' and 'cudnn_benchmark'.
Rename metric name of cublas and cudnn microbenchmark.

Bug bash - Rename bin name and metric name of cublas and cudnn microbenchmark

---

superbench/benchmarks/__init__.py
superbench/benchmarks/context.py
superbench/benchmarks/micro_benchmarks/computation_communication_overlap.py
superbench/benchmarks/micro_benchmarks/sharding_matmul.py
superbench/benchmarks/model_benchmarks/model_base.py

For distributed micro-benchmarks, add DistributedImpl and DistributedBackend arguments. Currently the benchmark 'computation_communication_overlap' and 'sharding_matmul' need to add these arguments.

Benchmarks: Add Feature - Add DistributedImpl and DistributedBackend arguments for micro benchmark.

---

superbench/benchmarks/micro_benchmarks/gemm_flops_performance.py

When specify precision in arguments, the validation checking of specified precision get wrong candidates to verify.

Benchmarks: Fix Bug - Fix typo in gemm-flops benchmark.

---

Makefile
superbench/common/utils/__init__.py
superbench/common/utils/file_handler.py
superbench/executor/executor.py
superbench/runner/playbooks/fetch_results.yaml
superbench/runner/runner.py
tests/runner/test_runner.py

Fetch benchmarks results on all nodes, will rsync after each benchmark.
The results directory structure on control node is as follows:
```
outputs/
└── datetime
├── nodes
│   └── node-0
│       ├── benchmarks
│       │   ├── benchmark-0
│       │   │   ├── rank-0
│       │   │   │   └── results.json
│       └── sb-exec.log
├── sb-run.log
└── sb.config.yaml
```

Runner - Fetch benchmarks results on all nodes

---

.gitmodules
third_party/Makefile

There is something wrong with git submodule's checkout in makefile during docker building because previously .git was excluded when ADD or COPY which is defined in .dockerignore. 
- Remove cuda-samples in .gitmodules.
- Add git clone in third_party/makefile

Benchmarks: Fix bug - fix bug of third_party/cuda-samples git checkout issue when building docker

---

.gitmodules
third_party/Makefile

Add FIO benchmark tool into third-party dependency.
- Add FIO submodule into third-party directory and modify Makefile to enable it.

Benchmarks: Build Pipeline - Add FIO benchmark tool

---

superbench/benchmarks/model_benchmarks/pytorch_base.py

Fix bug of VGG models failed on A100 GPU with batch_size=128.
- Add synchronize before delete self.model in _postprocess of superbench/benchmarks/model_benchmarks/pytorch_base.py
- Add if self._gpu_available check 
- Reorder del

Benchmarks: Fix Bug - Fix bug of VGG models failed on A100 GPU with batch_size=128

---

.gitmodules
dockerfile/cuda11.1.1.dockerfile
third_party/Makefile

Support rocm in third_party/makefile and add rccl-tests as a submodule with building logic.
- Support rocm in third_party/makefile
- Add rccl-tests as a submodule 
- Add build logic in third_party/Makefile for rccl-tests

Benchmarks: Build Pipeline - add rccl-tests as a submodule with building logic

---

superbench/benchmarks/micro_benchmarks/disk_performance.py
tests/benchmarks/micro_benchmarks/test_disk_performance.py

This commit adds readwrite I/O pattern for FIO benchmark. Read/write ratio is fixed at 4:1.

Benchmarks: Revise Benchmark - Add readwrite I/O pattern

---

superbench/benchmarks/micro_benchmarks/ib_loopback_performance.py

Remove ib device port info in command to fix bug of ib loopback.
- Remove ib device port info in command to fix bug of ib loopback

Benchmarks: Fix Bug - Remove ib device port info in command to fix bug of ib loopback 

---

superbench/benchmarks/micro_benchmarks/disk_performance.py
superbench/config/default.yaml
tests/benchmarks/micro_benchmarks/test_disk_performance.py

This commit revises disk performance benchmark, including:
1) Add missing benchmark name in default config;
2) Avoid using reserved character ':' in metric name.

Benchmarks: Code Revision - Revise metric name generation and default config for disk performance benchmark

---

superbench/benchmarks/micro_benchmarks/disk_performance.py

This commit fixes error of missing key 'percentile' in parsing FIO result.

Benchmarks: Fix bug - Fix missing key error in disk performance benchmark

---

superbench/benchmarks/model_benchmarks/pytorch_base.py
superbench/runner/runner.py

Add barrier before 'destroy_process_group' to resolve the bug due to when multi models in one model benchmark, some processes haven't finished the previous process group while others failed to initialize new process group for the next model on rocm4.x when running bert_models.
-  Add barrier before 'destroy_process_group'.

Bug: Fix Bug - Add barrier before 'destroy_process_group' in model benchmarks

---

superbench/benchmarks/build.sh
superbench/benchmarks/micro_benchmarks/cublas_function/CMakeLists.txt
superbench/benchmarks/micro_benchmarks/cuda_common.cmake
superbench/benchmarks/micro_benchmarks/cudnn_function/CMakeLists.txt
superbench/benchmarks/micro_benchmarks/gpu_sm_copy_performance/CMakeLists.txt
superbench/benchmarks/micro_benchmarks/kernel_launch_overhead/CMakeLists.txt

1. Do `enable_language(CUDA)` before using `CMAKE_CUDA_COMPILER_VERSION`
2. use `cmake --install` to install target which will call `cmake -P cmake_install.cmake` instead of `make Makefile` to avoid issue `make: *** No rule to make target 'install'.  Stop.`

Benchmarks: Code Revision - Revise CMake files for microbenchmarks.

---

superbench/cli/_commands.py
superbench/cli/_node_handler.py
tests/cli/test_sb.py

Integrate system info for node, add `sb node info` command.

CLI - Integrate system info for node

---

superbench/runner/runner.py
tests/runner/test_runner.py

Fix `torch.distributed` command for single node.

Bug - Fix torch.distributed command for single node

---

.github/workflows/build-image.yml
dockerfile/rocm4.0-pytorch1.7.0.dockerfile

Push Docker images in GitHub Action.

CI/CD - Push images in GitHub Action

---

superbench/config/amd_mi100_hpe.yaml
superbench/config/azure_ndv4.yaml
superbench/config/default.yaml

This commit fixes wrong parameters for gpu-sm-copy-bw call in configuration examples.

Benchmarks: Fix Bug - Fix wrong parameters for gpu-sm-copy-bw in configuration examples

---

third_party/Makefile

Update rccl-test git submodule to dc1ad48 which fix the bug of division by zero
- update rccl-test git submodule to dc1ad48

Benchmarks: Build Pipeline - Update rccl-test git submodule to dc1ad48

---

third_party/Makefile

Upgrade FIO benchmark tool from 3.27 to 3.28.

Benchmarks: Build Pipeline - Upgrade FIO benchmark tool

---

superbench/config/azure_ndv4.yaml
superbench/config/default.yaml
tests/runner/test_runner.py

Replace `-c` argument with `-N` for `numactl` since the old `-c`/`--cpubind` argument is deprecated.

Benchmark: Replace `-c` argument with `-N` for `numactl` in Configuration

---

superbench/benchmarks/base.py
superbench/benchmarks/registry.py
tests/benchmarks/test_registry.py

If `ignore_invalid` is True, and 'required' arguments are not set when register the benchmark, the arguments should be provided by user in config and skip the arguments checking.

Benchmarks: Add Feature - Add 'ignore_invalid' option when register benchmarks.

---

docs/getting-started/run-superbench.md

Minor doc change to highlight sb CLI version is independent of the sb container version.

Docs - Add a small note for using release container version

---

superbench/benchmarks/micro_benchmarks/_export_torch_to_onnx.py
superbench/runner/ansible.py
superbench/runner/playbooks/fetch_results.yaml
superbench/runner/runner.py
tests/ansible/tests/test_deploy.yaml
tests/runner/test_ansible.py

Fix issues for Ansible and benchmarks:
* Cleanup Ansible runner private data dir to avoid out of disk space issue when node number is large.
* Support both absolute and relative paths when fecth results.
* Use a deterministic image in Ansible test to avoid image update.
* Update logging format.
* Delete torch models and inputs after export.

Bug - Fix issues for Ansible and benchmarks

---

README.md
docs/getting-started/installation.mdx
docs/getting-started/run-superbench.md
docs/superbench-config.mdx
docs/user-tutorial/container-images.mdx
docs/user-tutorial/data-diagnosis.md
setup.py
superbench/__init__.py
superbench/config/amd_mi100_hpe.yaml
superbench/config/amd_mi100_z53.yaml
superbench/config/azure_ndmv4.yaml
superbench/config/azure_ndv4.yaml
superbench/config/default.yaml
tests/analyzer/test_rules.yaml
website/blog/2021-12-24-release-0-4.md
website/docusaurus.config.js
website/package-lock.json
website/package.json

Upgrade version and release note.
__Major Revision__
- Upgrade package versions
- Add release note for v0.4.0

Docs - Upgrade version and release note

---

docs/cli.md
superbench/benchmarks/base.py
superbench/cli/_benchmark_handler.py
superbench/cli/_commands.py
superbench/cli/_help.py
tests/benchmarks/model_benchmarks/test_model_base.py
tests/benchmarks/test_registry.py
tests/cli/test_sb.py

Add command `sb benchmark list` and `sb benchmark list-parameters` to support listing all optional parameters for benchmarks.
<details>
<summary>Examples</summary>
<pre>
$ sb benchmark list -n [a-z]+-bw -o table
Result
--------
mem-bw
nccl-bw
rccl-bw
</pre>
<pre>
$ sb benchmark list-parameters -n mem-bw
=== mem-bw ===
optional arguments:
--bin_dir str         Specify the directory of the benchmark binary.
--duration int        The elapsed time of benchmark in seconds.
--mem_type str [str ...]
Memory types to benchmark. E.g. htod dtoh dtod.
--memory str          Memory argument for bandwidthtest. E.g. pinned unpinned.
--run_count int       The run count of benchmark.
--shmoo_mode          Enable shmoo mode for bandwidthtest.
default values:
{'bin_dir': None,
'duration': 0, …

CLI - Add command sb benchmark [list,list-parameters]

---

superbench/benchmarks/micro_benchmarks/cublas_function/cublas_helper.cpp

Fix insecure issue of Multiplication result converted to larger type.
- Use a cast to ensure that the multiplication is done using the long long to avoid overflow.

Bug: Fix code incesure issue of integer overflow in cublas function

---

superbench/benchmarks/model_benchmarks/model_base.py
superbench/benchmarks/model_benchmarks/pytorch_base.py
superbench/runner/runner.py
tests/benchmarks/model_benchmarks/test_model_base.py
tests/runner/test_runner.py

Please write a brief description and link the related issue if have.
- Sync (do allreduce max) the E2E training results among all workers.
- Avoid using ':0' in metric name if there has only one rank having output.

Benchmarks: Add Feature - Sync the E2E training results among all workers for each step.

---

superbench/benchmarks/micro_benchmarks/rocm_common.cmake

Fix HIP_ARCHITECTURES is empty issue with cmake>=3.21.0.
Refer to https://github.com/ROCm-Developer-Tools/HIP/pull/2364

Bug - fix HIP_ARCHITECTURES is empty issue in cmake>=3.21.0

---

third_party/Makefile

Benchmarks: Build Pipeline - Make gpcnet only for cuda

---

superbench/benchmarks/model_benchmarks/pytorch_cnn.py

The BatchNorm operator is not numerically stable in fp16.  PyTorch documentation recommends to keep the BN op in fp32 for fp16 AMP models.  Refer to https://pytorch.org/docs/stable/amp.html#ops-that-can-autocast-to-float32.  Preserving BN in fp32 for superbench more accurately reflects real workloads.

Benchmarks - Keep BatchNorm as fp32 for pytorch cnn models cast to fp16

---

superbench/runner/playbooks/check_env.yaml
superbench/runner/runner.py

Fix env file path to absolute path in `docker exec`, in case there're mixed ssh and local connections or different users are used.

Bug - Fix env path to absolute path

---

superbench/benchmarks/model_benchmarks/pytorch_cnn.py
superbench/benchmarks/model_benchmarks/pytorch_lstm.py

Remove fp16  samples type converting time for cnn and lstm models.

Bug: Benchmarks - remove fp16  samples type converting time for cnn and lstm models

---

superbench/benchmarks/model_benchmarks/pytorch_cnn.py
superbench/benchmarks/model_benchmarks/pytorch_lstm.py

remove fp16 samples type converting time for training cnn and lstm inference.

Bug: Benchmarks - remove fp16 samples type converting time for training cnn and lstm inference

---

examples/benchmarks/fambench.py
superbench/benchmarks/docker_benchmarks/__init__.py
superbench/benchmarks/docker_benchmarks/fambench.py
tests/benchmarks/docker_benchmarks/test_fambench.py

Integrate FAMBench into superbench based on docker implementation:
https://github.com/facebookresearch/FAMBench
The script to run all benchmarks is:
https://github.com/facebookresearch/FAMBench/blob/main/benchmarks/run_all.sh

Benchmarks: Add Benchmark - Add FAMBench based on docker benchmark

---

docs/user-tutorial/result-summary.md

Fixes dead link in documentation: point to `../cli.md`

Docs - Update link to cli.md

---

setup.py

Force to fix ort version as '1.10.0' .
Bug in onnxruntime-gpu '1.11.0':

Bug - Force to fix ort version as '1.10.0'

---

superbench/benchmarks/model_benchmarks/model_base.py
superbench/benchmarks/model_benchmarks/pytorch_base.py
superbench/benchmarks/model_benchmarks/pytorch_bert.py
superbench/benchmarks/model_benchmarks/pytorch_cnn.py
superbench/benchmarks/model_benchmarks/pytorch_gpt2.py
superbench/benchmarks/model_benchmarks/pytorch_lstm.py
tests/benchmarks/model_benchmarks/test_pytorch_base.py

Fix bug of duration feature for model benchmarks in distributed mode.
- Add all_reduce to sync the result of is_finished(the function to judge whether the model benchmark should be stopped) in each step 
- to avoid inconsistency between different ranks to determine duration end (some rank may enter one more step and can never finish)
- Add torch.cuda.synchronize() before and after step time measuring in train_step() for all model benchmarks
- some operations in train_step() maybe async resulting incorrect step time records (for example, lstm)

Bug - Fix bug of duration feature for model benchmarks in distributed mode.

---

.github/workflows/build-image.yml
dockerfile/rocm5.1.1-pytorch1.10.0.dockerfile

Update rccl version and fix issue in rocm5.1.1 dockerfile.

Dockerfile: Update rccl version and fix issue in rocm5.1.1 dockerfile

---

dockerfile/cuda11.1.1.dockerfile
dockerfile/rocm4.0-pytorch1.7.0.dockerfile
dockerfile/rocm4.2-pytorch1.7.0.dockerfile
dockerfile/rocm5.0-pytorch1.9.0.dockerfile
dockerfile/rocm5.0.1-pytorch1.9.0.dockerfile
dockerfile/rocm5.1.1-pytorch1.10.0.dockerfile
superbench/benchmarks/micro_benchmarks/ib_validation_performance/CMakeLists.txt
third_party/Makefile

Fix cmake and build issues.
* Remove unnecessary boost build
* Remove user-agent for mlc
* Remove -j for third party to build each project in sequence
* Fix ansible collections installation path

Fix cmake and build issues

---

dockerfile/cuda11.1.1.dockerfile
dockerfile/rocm5.0.x.dockerfile
dockerfile/rocm5.1.x.dockerfile
docs/user-tutorial/benchmarks/micro-benchmarks.md
superbench/benchmarks/micro_benchmarks/ib_validation_performance.py
superbench/benchmarks/micro_benchmarks/ib_validation_performance/ib_validation_performance.cc
superbench/config/azure_ndmv4.yaml
superbench/config/azure_ndv4.yaml
superbench/config/default.yaml
superbench/runner/playbooks/check_env.yaml
superbench/runner/runner.py
tests/benchmarks/micro_benchmarks/test_ib_traffic_performance.py

Support multiple IB/GPU devices run simultaneously in ib validation benchmark.
- Revise ib_validation_performance.cc so that multiple processes per node could be used to launch multiple perftest commands simultaneously. For each node pair in the config, number of processes per node will run in parallel.
- Revise ib_validation_performance.py to correct file paths and adjust parameters to specify different NICs/GPUs/NUMA nodes.
- Fix env issues in Dockerfile for end-to-end test.
- Update ib-traffic configuration examples in config files.
- Update unit tests and docs accordingly.
Closes #326.

Support multiple IB/GPU in ib validation

---

dockerfile/cuda11.1.1.dockerfile
dockerfile/rocm5.0.x.dockerfile
dockerfile/rocm5.1.x.dockerfile

Fix incorrect ulimit nofile config in Dockerfile.
Instead of bash, sh is used by default where `echo` does not accept any parameters and `-e` is written into /etc/security/limits.conf.

Dockerfile - Fix incorrect ulimit config

---

docs/user-tutorial/benchmarks/micro-benchmarks.md
superbench/benchmarks/micro_benchmarks/ib_loopback_performance.py
tests/benchmarks/micro_benchmarks/test_ib_loopback_performance.py

Fix several issues in ib loopback benchmark:
* use `--report_gbits` and divide by 8 to get GB/s, previous results are MiB/s / 1000
* use the ib_write_bw binary built from third_party instead of system path
* update the metrics name so that different hca indices have same metric

Fix issues in ib loopback benchmark

---

docs/superbench-config.mdx
superbench/runner/runner.py
tests/runner/test_runner.py

Support `node_num: 1` in mpi mode, so that we can run mpi benchmarks in
both 1 node and all nodes in one config by changing `node_num`.
Update docs and add test case accordingly.

Runner - Support node_num=1 in mpi mode

---

superbench/benchmarks/micro_benchmarks/ib_loopback_performance.py
tests/benchmarks/micro_benchmarks/test_ib_loopback_performance.py

Fix potential port conflict due to race condition between time-to-check
to time-to-use, by binding the port all through.
Modify the function to resolve flake8 C901 while keeping the logic same.

Fix port conflict in ib loopback

---

superbench/benchmarks/micro_benchmarks/ib_validation_performance.py
tests/benchmarks/micro_benchmarks/test_ib_traffic_performance.py

Fix an unexpected result value (`-0.125`) issue in ib traffic benchmark when encountering `-1` in raw output
* Check if the value is valid before the base conversion
* Add a test case to cover this situation

Benchmarks: Fix Bug - Fix unexpected base conversion when the result value is negative in IB benchmark

---

superbench/runner/runner.py

Fix minimum timeout: use 60s if config is shorter.

Runner - Fix minimum timeout

---

superbench/benchmarks/micro_benchmarks/ib_validation_performance.py
superbench/benchmarks/micro_benchmarks/ib_validation_performance/ib_validation_performance.cc
tests/benchmarks/micro_benchmarks/test_ib_traffic_performance.py

Enable ib latency test in ib traffic validation distributed benchmark
As Perftest supports CUDA only in BW tests (Refer [perftest source code](https://github.com/linux-rdma/perftest/blob/23f7f8a56892bd9e00b6a4e8bd4bbfdbe122af47/src/perftest_parameters.c#L1652))
Remove `--use_cuda` option from cmd prefix if the test command is bw related

Enable latency test in ib traffic validation distributed benchmark

---

setup.py
superbench/common/utils/logging.py

Upgrade colorlog for [`$NO_COLOR`](https://no-color.org/) support.

Upgrade colorlog for NO_COLOR support

---

.codecov.yml
superbench/cli/_handler.py
superbench/runner/ansible.py
superbench/runner/runner.py
tests/cli/test_sb.py
tests/runner/test_runner.py

Add non-zero return code for `sb deploy` and `sb run` command when there're Ansible failures in control plane.
Return code is set to count of failure.
For failures caused by benchmarks, return code is still set per benchmark in results json file.
Resolves #410 and #411.

CLI - Add non-zero return code for `sb [deploy,run]`

---

setup.py

Update typing-extensions>=3.10 as recent mypy's update is failing cuda test pipeline.

Setup update typing-extensions version

---

superbench/benchmarks/micro_benchmarks/cublaslt_fp8_gemm/cublaslt_utils.h

I couldn't build the fp8 benchmark.
`
[ 25%] Building CXX object CMakeFiles/cublaslt_utils.dir/cublaslt_utils.cc.o
In file included from <scrubbed>/superbench/benchmarks/micro_benchmarks/cublaslt_fp8_gemm/cublaslt_utils.cc:4:
<scrubbed>/superbench/benchmarks/micro_benchmarks/cublaslt_fp8_gemm/cublaslt_utils.h: In function ‘void checkCublasStatus(cublasStatus_t)’:
<scrubbed>/superbench/benchmarks/micro_benchmarks/cublaslt_fp8_gemm/cublaslt_utils.h:15:20: error: ‘logic_error’ is not a member of ‘std’
15 |         throw std::logic_error("cuBLAS API failed");
|                    ^~~~~~~~~~~
<scrubbed>/superbench/benchmarks/micro_benchmarks/cublaslt_fp8_gemm/cublaslt_utils.cc: In member function ‘size_t cublasLtGemm::GetAlgorithm(int, size_t)’: …

Benchmarks - Fix missing include in FP8 benchmark

---

docs/cli.md
superbench/benchmarks/model_benchmarks/pytorch_bert.py
superbench/cli/_commands.py
superbench/cli/_handler.py
superbench/runner/playbooks/deploy.yaml
superbench/runner/runner.py
tests/cli/test_sb.py

Support `--no-image-pull` in `sb deploy` to skip image pull to use local cached images.

Support `sb deploy` without pulling image

---

dockerfile/rocm5.1.x.dockerfile

The commit(e08b6d3a1cc32ac978182acd0be0ce197ca18e0d) installs a rccl version which is causing "undefined symbol: ncclGetLastError" while trying to import torch. Revert it to avoid the error.

Dockerfile: Remove fixed rccl version in rocm5.1.x docker file

---

third_party/Makefile

Add suppport to install cpu-only perftest in makefile.

Benchmarks: Build Pipeline - Add suppport for cpu-only perftest in makefile

---

setup.py

Limit ansible_runner version to less than 2.3.2 for Python3.6.

Limit ansible_runner version for Python3.6

---

.azure-pipelines/cpu-unit-test.yml
.azure-pipelines/cuda-unit-test.yml
dockerfile/rocm5.0.x.dockerfile
setup.py

Pin setuptools version to [v65.7.0](https://setuptools.pypa.io/en/latest/history.html#v65-7-0) to avoid breaking changes pypa/setuptools#2497 since v66.0.0, see pypa/setuptools#3772 for reference.

Pin setuptools version to v65.7.0

---

superbench/benchmarks/model_benchmarks/pytorch_base.py

Fix potential barrier timeout in init_process_group due to race condition of using the same port. Change to different ports when running multiple models sequentially in one process.
For example, when running vgg11/13/16/19, will use port 29501~29504 respectively.

Benchmark - Fix torch.dist init issue with multiple models

---

docs/user-tutorial/benchmarks/micro-benchmarks.md
superbench/benchmarks/micro_benchmarks/cublaslt_function.py
tests/benchmarks/micro_benchmarks/test_cublaslt_function.py

Support batch and shape range with multiplication factors in cublaslt gemm benchmark.

Benchmark - Support batch/shape range in cublaslt gemm

---

superbench/benchmarks/model_benchmarks/pytorch_base.py
superbench/benchmarks/model_benchmarks/pytorch_bert.py
superbench/benchmarks/model_benchmarks/pytorch_gpt2.py

Support Transformer Engine FP8 in existing PyTorch BERT/GPT2 models by converting linear/layernorm to TE layers.

Benchmarks - Support TE FP8 in BERT/GPT2 models

---

superbench/monitor/monitor.py

Looks `grep cgroup /proc/filesystems` doesn't work for NDv4 whose cgroup version is v1, but the result of this command got v2 for NDv4. Instead, checking the file existence to judge the cgroup version.

Monitor - Fix the cgroup version checking logic.

---

setup.py
superbench/benchmarks/micro_benchmarks/cublaslt_gemm/cublaslt_gemm.cu
superbench/benchmarks/micro_benchmarks/cublaslt_gemm/cublaslt_utils.cc
superbench/benchmarks/micro_benchmarks/cublaslt_gemm/cublaslt_utils.h

Fix matrix size overflow issue when cast from int to size_t implicitly.

Benchmark - Fix matrix size overflow issue in cuBLASLt GEMM

---

superbench/benchmarks/micro_benchmarks/dist_inference.py

This commit fixes wrong `torch.empty_like` usage and missing dtype and device argument in communication wrappers.

Revise Code - Fix wrong torch usage in communication wrapper for Distributed Inference Benchmark

---

superbench/common/utils/device_manager.py
superbench/monitor/monitor.py
superbench/monitor/record.py
superbench/runner/runner.py
tests/monitor/test_monitor.py
tests/monitor/test_monitor_record.py

Collect realtime GPU power when benchmarking.

Monitor - Collect realtime GPU power when benchmarking.

---

docs/user-tutorial/benchmarks/micro-benchmarks.md

Fix wrong unit of cpu-memory-bw-latency in doc.

Doc - Fix wrong unit of cpu-memory-bw-latency in doc

---

superbench/benchmarks/micro_benchmarks/dist_inference.py

This commit revises distributed inference benchmark to give a unified step time result by taking maximum step times of different GPUs.

Benchmarks - Revise step time collection in distributed inference benchmark

---

docs/superbench-config.mdx
superbench/benchmarks/model_benchmarks/model_base.py
tests/benchmarks/model_benchmarks/test_model_base.py

Model benchmarks can stop due to `num_steps` or `duration` config which will take effect when the value is set greater than 0.
If both are set greater than 0, the earliest condition reached will work.

ModelBenchmarks - Fix early stop logic due to num_steps.

---

docs/user-tutorial/system-config.md

Kernel_parameters and kernel_modules command and examples are exchanged.

Docs - Fix typo on kernel_parameters and kernel_modules in system-config

---

setup.py
superbench/runner/ansible.py
superbench/runner/runner.py

Add signal handler in runner to gracefully exit when receiving SIGINT (<kbd>Ctrl</kbd>+<kbd>C</kbd>) or SIGTERM during benchmark execution.

Runner - Add signal handler in runner

---

docs/user-tutorial/benchmarks/micro-benchmarks.md

Modify link for Nvidia bandwidth test tool
previous link is 404
update the link value to https://github.com/NVIDIA/cuda-samples/tree/master/Samples/1_Utilities/bandwidthTest

Doc - Update outdate references in micro-benchmarks.md

---

.github/workflows/build-image.yml

clean more disk space to fix rocm building image pipeline.

CI/CD: pipeline - clean more disk space to fix rocm building image pipeline

---

superbench/benchmarks/micro_benchmarks/directx_gpu_encoding_latency.py

use absolute path for input file DirectXEncodingLatency.

Benchmarks: bug fix - use absolute path for input file in DirectXEncodingLatency

---

superbench/common/devices/gpu.py
superbench/runner/runner.py
tests/runner/test_runner.py

This PR has following changes
- torch.distributed.launch changed to torchrun. torch.distributed.launch is deprecated in latest Pytorch and is recommended to move to torchrun - https://pytorch.org/docs/stable/elastic/run.html
- Changes to AMD GPU detection logic. The AMD GPU detection logic throws warning when containers have only renderD in /dev/dri, this change would resolve those warnings

Benchmarks: model benchmarks - change torch.distributed.launch to torchrun

---

dockerfile/cuda11.1.1.dockerfile
dockerfile/rocm5.0.x.dockerfile
dockerfile/rocm5.1.x.dockerfile

Update mlc version into 3.10 for cuda and rocm dockerfiles to be consistent with cuda12 dockerfile

Dockerfile - update mlc version into 3.10 for cuda and rocm dockerfiles

---

superbench/benchmarks/micro_benchmarks/gpu_burn_test.py
tests/benchmarks/micro_benchmarks/test_gpu_burn_test.py

remove cp ptx file in gpu burn test since the command is run inside self.args.bin_dir dir.
https://github.com/microsoft/superbenchmark/blob/d246bab430adeb461072918a551b2e2b68c9bce5/superbench/benchmarks/micro_benchmarks/micro_base.py#L183

Bug Fix - remove cp ptx file command in gpu burn test 

---

superbench/benchmarks/micro_benchmarks/cublaslt_function.py
superbench/benchmarks/micro_benchmarks/cublaslt_gemm/cublaslt_gemm.cu
superbench/benchmarks/micro_benchmarks/cublaslt_gemm/cublaslt_utils.cc
tests/benchmarks/micro_benchmarks/test_cublaslt_function.py

add int8 support for cublaslt function.

Benchmarks: micro benchmarks - add int8 support for cublaslt function

---

superbench/benchmarks/micro_benchmarks/rocm_gemm_flops_performance.py
tests/benchmarks/micro_benchmarks/test_rocm_gemm_flops_performance.py

add initialization options for rocm gemm flops.

Benchmarks: Micro benchmark - add initialization options for rocm gemm flops

---

superbench/benchmarks/micro_benchmarks/gpu_copy_performance/CMakeLists.txt

`add_compile_options` will not work for ROCm build, change it to setting `CMAKE_CXX_FLAGS`.

Benchmark: Revision - Fix -O2 option passing in gpu_copy ROCm build

---

.github/workflows/build-image.yml
dockerfile/cuda12.2.dockerfile
third_party/Makefile

Upgrade nccl tests to resolve all gather hang issue in cuda12.2 docker.

Benchmarks: Build Pipeline - fix nccl and nccl test version to 2.18.3 to resolve hang issue in cuda12.2 docker

---

setup.py
superbench/config/default.yaml
superbench/executor/executor.py
superbench/runner/runner.py
tests/executor/test_executor.py

Update `omegaconf` version to [2.3.0](https://pypi.org/project/omegaconf/2.3.0/) as omegaconf 2.0.6 has a non-standard dependency specifier PyYAML>=5.1.*. pip 24.1 will enforce this behaviour change.
Discussion can be found at https://github.com/pypa/pip/issues/12063

Update omegaconf version to 2.3.0

---

setup.py

* https://pypi.org/project/types-pkg-resources/
* Use types-setuptools instead

Use `types-setuptools` as `types-pkg_resources` is Yanked

---

dockerfile/cuda12.2.dockerfile
dockerfile/cuda12.4.dockerfile
superbench/runner/runner.py

Add 10-hpcx.sh to /etc/profile.d
Update the Docker exec command to ensure a persistent HPCX environment.

Bug Fix - Update Docker Exec Command for Persistent HPCX Environment

---

superbench/executor/executor.py
superbench/runner/runner.py
tests/executor/test_executor.py
tests/runner/test_runner.py

* Fix executor for Benchmark Execution Without Explicit Framework Field
* Fix mca misspell issue
* Timeout should be None if it is not explicated

Bug - Fix issues caused by omegaconf version update 

---

setup.py

Limit protobuf version to be 3.20.x due to onnx reqirement

Limit protobuf version to be 3.20.x

---

dockerfile/cuda12.4.dockerfile

fix bug in cuda 12.4 docker file
- upgrade nccl due to OOM bug in nccl v2.20 graph mode
- install ucx 1.16 for mutli thread support for mpi in ib-traffic

Dockerfile - upgrade nccl version and install ucx to fix bug in cuda 12.4 docker file

---

.github/workflows/build-image.yml
dockerfile/rocm6.2.x.dockerfile
superbench/common/utils/device_manager.py

Dockerfile - Add ROCm6.2 dockerfile

---

docs/user-tutorial/data-diagnosis.md
docs/user-tutorial/result-summary.md
website/package-lock.json

In result-summary.md line 73-74, the example of kernel-launch used metrics 'kernel-launch/event_overhead' and 'kernel-launch/wall_overhead'.
But in micro-benchmarks.md line 20-21, the metric names are described as 'kernel-launch/event_time' and ' kernel-launch/wall_time'.
Solution: Use identical metric names described in micro-benchmarks.md.
https://github.com/microsoft/superbenchmark/issues/649
- Major Revision A
- Major Revision B
- ...
- Minor Revision A
- Minor Revision B
- ...

Docs - Fix metrics name in user tutorial

---

.github/workflows/build-image.yml

Update image build.
* Remove ROCm 6.0 image due to outdated packages
* Remove build tag for ROCm
* Preserve build cache for 30 days

CI/CD - Update Image Build Pipeline

---

superbench/benchmarks/micro_benchmarks/gpu_copy_performance/gpu_copy.cu

The current GPU Copy BW Performance fails on Nvidia Grace systems. This is due to the memory only numa node and thus the numa_run_on_node  fails for such nodes and halts completely.
This fix checks for the presence of assigned CPU cores for the numa node, on checking if it has no cpu cores assigned, it skips that specific node during the args creation and continues.

Bug Fix - Fix numa error on grace cpu in gpu-copy

---

tests/benchmarks/model_benchmarks/test_pytorch_base.py

Fix cache tests issues with cuda 12.4 and pytorch 2
https://pytorch.org/docs/stable/notes/cuda.html#cuda-memory-management:
```
PyTorch uses a caching memory allocator to speed up memory allocations. This allows fast memory deallocation without
device synchronizations. However, the unused memory managed by the allocator will still show as if used in nvidia-smi. 
You can use memory_allocated() and max_memory_allocated() to monitor memory occupied by tensors, and use 
memory_reserved() and max_memory_reserved() to monitor the total amount of memory managed by the caching allocator. 
Calling empty_cache() releases all unused cached memory from PyTorch so that those can be used by other GPU 
applications. However, the occupied GPU memory by tensors will not be freed so it can not increase the …
```

fix cache tests issues with cuda 12.4 and pytorch 2

---

superbench/benchmarks/micro_benchmarks/cuda_gemm_flops_performance.py

Introduce architecture support for version 10.0 in gemm-flops.

Microbenchmark: gemm-flops - Add arch support for 10.0

---

.pre-commit-config.yaml

flake8 has moved away from gitlab to github. 
Updating the repo path int he pre commit config.

Flake8 repo from github

---

superbench/benchmarks/micro_benchmarks/tensorrt_inference_performance.py

Today I was running a benchmark on my machine. And encountered a fancy issue with tensorsort-inference.
I got code 33, which according to the source code is:
```
MICROBENCHMARK_RESULT_PARSING_FAILURE = 33
```
I dived deep into the code and found out the following problem. The parser stumbled upon getting to the following line:
```
[11/28/2024-17:03:11] [I] Latency: min = 7.2793 ms, max = 10.1606 ms, mean = 7.41642 ms, median = 7.39551 ms, percentile(99%) = 8 ms
```
I ran it separately on the code and found out that the regular expression was not suitable for the cases like this, when you encounter an INT as a result in milliseconds.
That's why this pull request is created.
I came up with the closest possible regular expression to fix this issue and not to introduce any …

Bug - Fix tensorrt-inference parsing

---

superbench/benchmarks/micro_benchmarks/nvbandwidth.py
tests/benchmarks/micro_benchmarks/test_nvbandwidth.py

Root Cause:
1. '_get_all_test_cases()' was called in '_parser' while '_parser' was defined in the base class.
2.  in '_get_all_test_cases()', cmd path was not included.
Fix:
1. Remove '_get_all_test_cases()' from '_parser'.
2. Construct path for cmd.

Bugfix: Avoid Unintended nvbandwidth Function Calls in All Benchmarks

---

.mypy.ini

This enhancement addresses an issue in mypy where it may report missing pkg_resources even when ignore_missing_imports = True is set and the package is installed. Adding this configuration ensures that pkg_resources is properly skipped during type checking.

Lint: Enhancement of ignoring errors for import pkg_resources

---

.github/workflows/build-image.yml

Due to the matrix strategy’s default "fail-fast" setting. In GitHub Actions, when running a job with a matrix, the individual configurations run in parallel. By default, if one matrix job (for example, the one labeled "rocm6_2_rocm6_2_x_superbe") fails, the remaining parallel jobs are canceled automatically.
In our current build image pipeline, the arm64 build job always are canceled by the rocm build job. So, using a non-existent label in the job config to prevent rocm build job from scheduling for a temporary solution.

CI/CD - Update label in the ROCm image build

---

superbench/benchmarks/model_benchmarks/megatron_gpt3.py

Summary
Deepseek currently registers two benchmarks using the same identifier, causing a naming conflict.
Change
Rename each benchmark so that both have unique, descriptive names.

Bugfix: deepseek benchmark names conflict

---

superbench/benchmarks/micro_benchmarks/dist_inference_cpp/dist_inference.cu

change cublasLtMatmulDescCreate scaleType  from CUDA_R_32F to CUDA_R_16F in FP16 dist inference to fix cublaslt error.

Benchmarks: micro benchmarks - change cublasLtMatmulDescCreate scaleType  from CUDA_R_32F to CUDA_R_16F in FP16 dist inference 

---

superbench/benchmarks/model_benchmarks/model_base.py
superbench/benchmarks/model_benchmarks/pytorch_bert.py
superbench/benchmarks/model_benchmarks/pytorch_cnn.py
superbench/benchmarks/model_benchmarks/pytorch_gpt2.py
superbench/benchmarks/model_benchmarks/pytorch_llama.py
superbench/benchmarks/model_benchmarks/pytorch_lstm.py
superbench/benchmarks/model_benchmarks/pytorch_mixtral_impl.py
tests/benchmarks/model_benchmarks/test_model_base.py

add option to exclude data copy time in model benchmarks.
- add an option --exclude_copy_time
- move start time after data copy finish in measured time

Benchmark: Model benchmark - add option to exclude data copy time in model benchmarks
